global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['tasks.node_exporter:9100']

  - job_name: 'pi_temp_exporter'
    static_configs:
      - targets: ['tasks.pi_temp_exporter:9300']
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']


